# Generated by Django 3.1.3 on 2023-07-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='editedPicture',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='package',
            name='totalPicture',
            field=models.IntegerField(default=300),
        ),
    ]
