# Generated by Django 3.1.3 on 2023-08-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phnNum',
            field=models.BigIntegerField(default=880),
        ),
    ]
